sudo: required
services:
  - docker 

before_install:
  - docker build -t georgemathewk/docker-react -f Dockerfile.dev .  

script:  
  - docker run georgemathewk/docker-react npm run test -- --coverage